name: release-theme
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  check_if_version_upgraded:
    runs-on: ubuntu-latest
    outputs:
      is_upgraded_version: ${{ steps.check_version.outputs.is_upgraded_version }}
      to_version: ${{ steps.check_version.outputs.to_version }}
      is_pre_release: ${{ steps.check_version.outputs.is_pre_release }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check_version
        run: |
          # Add your version checking logic here
          echo "is_upgraded_version=true" >> $GITHUB_OUTPUT
          echo "to_version=1.0.0" >> $GITHUB_OUTPUT
          echo "is_pre_release=false" >> $GITHUB_OUTPUT

  create_github_release:
    runs-on: ubuntu-latest
    needs: check_if_version_upgraded
    if: needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true'
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
            
        - name: Install dependencies
          run: npm install --legacy-peer-deps
          
        - name: Build Keycloak theme
          run: CI=false npm run build-keycloak-theme
          
        - uses: softprops/action-gh-release@v2
          with:
              name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
              tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
              target_commitish: ${{ github.head_ref || github.ref }}
              generate_release_notes: true
              draft: false
              prerelease: ${{ needs.check_if_version_upgraded.outputs.is_pre_release == 'true' }}
              files: build_keycloak/keycloak-theme-*.jar
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}